version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: cron
      cronjob: '30 1 1,15 * *'
      timezone: America/New_York
    groups:
      patch-and-minor:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
