version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: daily
      time: '09:00'
      timezone: America/New_York
    groups:
      patch-and-minor:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
