require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: disable

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# RSpec Cops
RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
